<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'TALAIS Report' }}</title>
    <style>
        @page { margin: 18mm 12mm 14mm 12mm; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 9pt; color: #1f2937; }
        .header { text-align: center; margin-bottom: 8px; }
        .header h1 { margin: 0; font-size: 12pt; letter-spacing: 1px; }
        .header h2 { margin: 2px 0; font-size: 10pt; }
        .header p { margin: 0; font-size: 8pt; color: #4b5563; }
        .meta { margin-top: 8px; margin-bottom: 6px; font-size: 8pt; }
        .meta td { padding: 1px 6px; }
        table.data { width: 100%; border-collapse: collapse; font-size: 8pt; }
        table.data th, table.data td { border: 1px solid #4b5563; padding: 3px 4px; vertical-align: middle; }
        table.data thead { background: #1e3a5f; color: white; }
        table.data thead th { font-weight: 600; }
        .small { font-size: 7pt; color: #6b7280; }
        .signature { width: 100%; margin-top: 28px; font-size: 8pt; }
        .signature td { padding: 4px; }
        .signature .line { border-bottom: 1px solid #1f2937; height: 14px; }
        .footer { margin-top: 22px; font-size: 7pt; color: #6b7280; text-align: center; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .strong { font-weight: 700; }
        .badge-pass { color: #047857; font-weight: 700; }
        .badge-fail { color: #b91c1c; font-weight: 700; }
    </style>
</head>
<body>
    <div class="header">
        <p>Republic of the Philippines</p>
        <p>Department of Education</p>
        <h1>{{ $school['name'] ?? 'Musuan Integrated School' }}</h1>
        <p>
            {{ $school['division'] ?? '' }}
            @if (!empty($school['district'])) • {{ $school['district'] }} @endif
            @if (!empty($school['municipality'])) • {{ $school['municipality'] }} @endif
        </p>
        <h2>{{ $title }}</h2>
        @if (!empty($subtitle))
            <p class="small">{{ $subtitle }}</p>
        @endif
    </div>

    @yield('content')

    <div class="footer">
        Generated by TALAIS on {{ now()->format('M d, Y h:i A') }} • School ID {{ $school['school_id'] ?? '300003' }}
    </div>
</body>
</html>
